- name: MapR | Post Install | Stop Zookeeper before applying post installation
  service: name=mapr-zookeeper state=started
  when:  inventory_hostname in groups['mapr-zookeeper']
  tags: package

- name: MapR | Post Install | Start warden before applying post installation
  service: name=mapr-warden state=restarted

- name: MapR | Post Install | Give full permission to mapr user
  command: /opt/mapr/bin/maprcli acl edit -type cluster -user mapr:fc
  retries: 10
  delay: 20
  register: result
  until: result.stdout.find('Couldn\'t connect to the CLDB service') == -1
  when:  inventory_hostname == groups['mapr-client-node'][0]

- name: MapR | Post Install | Enable all feature for the cluster ( for version upgrade )
  command: /opt/mapr/bin/maprcli cluster feature enable -all
  when:  inventory_hostname == groups['mapr-client-node'][0]

- name: MapR | Post Install | Get the full version id from the cluster
  command: cat /opt/mapr/MapRBuildVersion
  register: mapr_full_version
  when:  inventory_hostname == groups['mapr-client-node'][0]

- name: MapR | Post Install | Apply new version info to avoid mapr alarm
  command: /opt/mapr/bin/maprcli config save -values "{ mapr.targetversion {{ ":" }} "{{ mapr_full_version.stdout }}" }"
  when: inventory_hostname == groups['mapr-client-node'][0]

- name: MapR | Post Install | Create a fake nfs path for trial licence
  file: path=/mapr/{{ mapr.cluster_name }} state=directory recurse=yes owner=mapr group=mapr mode="0755"
  when: licence_type == 'trial'

- name: MapR | Post Install | Install Python dependencies
  package: name="{{ item }}"
  with_items:
   - numpy
   - scipy
  tags: package
