
- hosts: localhost
  gather_facts: yes

- hosts: all:!localhost
  gather_facts: no
  serial: 1
  tasks:
    - name: Remove old vm fingerprints
      command: ssh-keygen -R {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
        - "{{ inventory_hostname }}.local"
        - "{{ ansible_host }}"
      delegate_to: localhost

- hosts: all:!localhost
  gather_facts: no
  roles:
    - { role: kvm-reset-vms, tags: [ kvm-reset-vms ] }