---
- hosts: localhost

- hosts: mapr-node:mapr-ha-node:es-cluster
  any_errors_fatal: true
  roles:
    - { role: hosts-reset,
        when: "{{ inventory_hostname in groups['mapr-node'] or inventory_hostname in groups['mapr-ha-node']}}",
        tags: ["hosts-reset", "hosts-add-group"] }
    - { role: hosts-add-group, dynamic_hosts_group: "mapr-node",
        when: "{{ inventory_hostname in groups['mapr-node'] or inventory_hostname in groups['mapr-ha-node']}}",
        tags: "hosts-add-group" }
    - { role: hosts-add-group, dynamic_hosts_group: "mapr-ha-node",
        when: "{{ inventory_hostname in groups['mapr-node'] or inventory_hostname in groups['mapr-ha-node']}}",
        tags: "hosts-add-group"  }
    - { role: hosts-add-static,
        static_hosts: "{{ additionnal_hosts }}",
        when: "{{ additionnal_hosts is defined }}",
        tags: hosts-add-static
    }

- hosts: mapr-ha-node
  any_errors_fatal: true
  roles:
    - { role: common, tags: [ common ] }
    - { role: ssh-keys, user: "root", tags: [ mapr-install-sshkeys ] }
    - { role: mapr-haproxy, tags: [ mapr-install-haproxy ] }
    - { role: mysql-server, tags: [ mapr-install-mysql ] }
    - { role: mysql-replication, tags: [ mapr-install-mysql-replication ], when: "{{ groups['mapr-ha-node']|length > 1 }}" }

- hosts: mapr-mock-ldapserver
  any_errors_fatal: true
  roles:
    - { role: ldap-server, when: "{{ use_ldap }}", tags: [ mapr-install-ldap-server ] }

- hosts: mapr-node
  any_errors_fatal: true
  serial: "{{ rolling_update | default(false) |ternary('30%', '100%') }}"
  roles:
    - { role: common, tags: [ common ] }
    - { role: mapr-base-install, tags: [ mapr-install-base ] }
    - { role: ssh-keys, user: "mapr", tags: [ mapr-install-sshkeys ] }
    - { role: ssh-keys, user: "root", tags: [ mapr-install-sshkeys ] }
    - { role: ldap-client, when: "{{ use_ldap }}", tags: [ mapr-install-ldap-client ] }

# Install License needs all zookeeper started
- hosts: mapr-node
  any_errors_fatal: true
  serial: "100%"
  roles:
    - { role: mapr-license, tags: [ mapr-install-license ] }

- hosts: mapr-node
  any_errors_fatal: true
  serial: "{{ rolling_update | default(false) | ternary('30%', '100%') }}"
  roles:
    - { role: mapr-base-nfs, tags: [ mapr-install-nfs ] }
    - { role: mapr-base-postinstall, tags: [ mapr-post-install ] }
    - { role: mapr-base-patches, when: mapr_release_version != "5.2.1", tags: [ mapr-install-patches ] }
