
- name: KVM | Domain | Disable administrators SSH Keys for user root
  remote_user: centos
  authorized_key: user=root key="{{ lookup('file', '{{ inventory_dir }}/../common_vars/ssh-keys/root/enabled/ansible')}}" manage_dir=yes state=absent

- name: KVM | Domain | Enable administrators SSH Keys for admin users
  remote_user: centos
  authorized_key: user=root key="{{ lookup('file', item )}}" manage_dir=yes
  with_fileglob:
    - '{{ inventory_dir }}/../common_vars/ssh-keys/root/enabled/*'
  become: yes

- name: KVM | Domain | Gathering Facts now
  action: setup

# Specific to CentOS 6
# Centos 6 doesn't resize rootfs on start
- name: KVM | Domain | Configure Yum.conf
  template: src=etc_yum.conf.j2 dest=/etc/yum.conf owner=root group=root mode=0755

- name: KVM | Domain | Add Centos Repo
  template:
    src: "{{ item.src }}"
    dest: "/etc/yum.repos.d/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "etc_yum.repos.d_epel.repo.j2", dest: "epel.repo" }

- name: KVM | Domain | Disable DNS update (disable default dns config that causes lag on gathering fact)
  become: true
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 regexp="^PEERDNS" line="PEERDNS=no"

- name: KVM | Domain | Remove nameserver in resolv.conf
  become: true
  lineinfile: dest=/etc/resolv.conf regexp="nameserver" state=absent

- name: KVM | Domain | Install dependencies (CloudInit)
  yum: pkg={{ item }}
  with_items:
    - cloud-utils
    - dracut-modules-growroot
  when:  ansible_distribution_major_version == '6'

- name: KVM | Domain | Check if root partition needs to be resized
  become: yes
  shell: growpart -N /dev/vda 1 2>&1
  register: growpart_status
  ignore_errors: true
  when:  ansible_distribution_major_version == '6'

- name: KVM | Domain | Resize root volume
  become: yes
  command: growpart /dev/vda 1
  when:  growpart_status.stdout.find('NOCHANGE') == -1 and ansible_distribution_major_version == '6'

- name: KVM | Domain | Restart to apply resize
  command: reboot
  become: true
  when:  growpart_status.stdout.find('NOCHANGE') == -1 and ansible_distribution_major_version == '6'

- name: KVM | Domain | Wait for restart
  delegate_to: localhost
  wait_for: port=22 host="{{ ansible_host }}" delay=5

