---
- name: Ansible Host | SSH | Check
  stat: path=~/.ssh/config
  register: sym
  tags: sshconfig

- name: Ansible Host | SSH | Check if the local config exists, otherwise, create it
  template: src=ssh_config.j2 dest=~/.ssh/config mode=0644
  when: sym.stat.islnk is not defined
  tags: sshconfig

- name: Ansible Host | SSH | Enable ServerAliveInterval
  lineinfile: dest=~/.ssh/config regexp="^ServerAliveInterval(.)*" line="ServerAliveInterval {{ ssh_server_alive_interval }}"
  tags: sshconfig

- name: Ansible Host | SSH | Enable ServerAliveCountMax
  lineinfile: dest=~/.ssh/config regexp="^ServerAliveCountMax(.)*" line="ServerAliveCountMax {{ ssh_server_alive_count_max }}"
  tags: sshconfig