
- name: MapR | Hue | Installation de Hue sur les noeuds clients
  package: pkg=mapr-hue-{{ mapr_hue_version }}* state=latest
  tags: package

- name: MapR | Hue | Installation de Livy noeuds clients
  package: pkg=mapr-hue-livy-{{ mapr_hue_version }}* state=latest
  tags: package

- name: MapR | Hue | Configure Hue.ini
  template: src=hue.ini.j2 dest=/opt/mapr/hue/hue-{{ mapr_hue_version }}/desktop/conf/hue.ini backup=no

- name: MapR | Hue | Configure warden for multiple hue (non active/passive)
  lineinfile: dest={{ item }} regexp="services=hue" line="services=hue:all"
  with_items:
    - "/opt/mapr/hue/hue-{{ mapr_hue_version }}/desktop/conf/warden.hue.conf"
    - "/opt/mapr/conf/conf.d/warden.hue.conf"
  notify: Restart Warden


- name: MapR | Hue | Configure warden for multiple livy (non active/passive)
  lineinfile: dest={{ item }} regexp="services=livy" line="services=livy:all"
  with_items:
    - "/opt/mapr/hue/hue-{{ mapr_hue_version }}/desktop/conf/warden.livy.conf"
    - "/opt/mapr/conf/conf.d/warden.livy.conf"
  notify: Restart Warden

- meta: flush_handlers

- include: configure.yml

- name: MapR | Hue | Restart Hue
  command: maprcli node services -name hue -action restart -nodes {{ inventory_hostname }}
  register: hue_service_state
  retries: 5
  delay: 20
  until: "'hue is not configured on node' not in hue_service_state.stdout "


- name: MapR | Hue | Wait for website
  wait_for: port={{ hue.webserver_port }}

- name: MapR | Hue | Verify ldap connectivity if required
  command: /opt/mapr/hue/hue-{{ mapr_hue_version }}/build/env/bin/hue sync_ldap_users_and_groups
  register: sync_result
  failed_when: "'ldap_open_defconn: successful' not in sync_result.stderr"
  when: "{{ use_ldap }}"

- name: MapR | Hue | Lookup is Hue Mysql db is already initialized
  command: mysql --database {{ hue.db_name }} -u {{ hue.db_user }} -p{{ hue.db_passwd }} -h {{ groups['mapr-ha-node'][0] }} -e "show tables;"
  register: mysql_result
  changed_when: "{{ 'auth_group' not in mysql_result.stdout }}"

- name: MapR | Hue | Initialize MySQL db for Hue
  command: /opt/mapr/hue/hue-{{ mapr_hue_version }}/build/env/bin/hue syncdb --noinput
  when: "{{ 'auth_group' not in mysql_result.stdout}}"

- name: MapR | Hue | Lookup is Hue Mysql db is already migrated
  command: mysql --database {{ hue.db_name }} -u {{ hue.db_user }} -p{{ hue.db_passwd }} -h {{ groups['mapr-ha-node'][0] }} -e "show tables;"
  register: mysql_result
  changed_when: "{{ 'desktop_settings' not in mysql_result.stdout }}"

- name: MapR | Hue | Apply migration MySQL db for Hue
  command: /opt/mapr/hue/hue-{{ mapr_hue_version }}/build/env/bin/hue migrate
  when: "{{ 'desktop_settings' not in mysql_result.stdout}}"

- name: MapR | Hue | Restart Hue for refreshing ldap and mysql config
  command: maprcli node services -name hue -action restart -nodes {{ inventory_hostname }}

