---
- name: MapR | Kafka | Check mount NFS
  shell:  mount -t nfs
  register: nfsmount
  retries: 30
  until: "'/mapr' in nfsmount.stdout"
  delay: 1

- name: MapR | Kafka | Check if the /mapr/{{ mapr.cluster_name }}/var/mapr/local/kafka/{{ inventory_hostname }} volume exists
  stat: path=/mapr/{{ mapr.cluster_name }}/var/mapr/local/kafka/{{ inventory_hostname }}
  register: nfskafkavolume
  retries: 30
  until: nfskafkavolume.stat.islnk is defined
  delay: 1
  ignore_errors: true

- name: MapR | Kafka | Create the /var/mapr/local/kafka/{{ inventory_hostname }} volume
  command: |
    maprcli volume create
      -name mapr.kafka.{{ inventory_hostname }}
      -path /var/mapr/local/kafka/{{ inventory_hostname }}
      -replication 1
      -minreplication 1
      -createparent 1
  become_user: mapr
  become: true
  run_once: true
  when: nfskafkavolume.stat.islnk is not defined
