- name: MapR | Kafka | Wait for kafka server to be ready
  wait_for: port={{ kafka.port }} delay=10
  tags: ["smoke-test-kafka", "smoke-test"]

- name: MapR | Kafka | Create a test topic
  command: >
    {{ kafka_home_dir }}/bin/kafka-topics.sh
       --create
       --topic {{ kafka_test_topic_name }}
       --zookeeper {{ inventory_hostname }}:{{ zookeeper.port }}
       --partition {{ kafka_test_partition_value }}
       --replication-factor {{ kafka_test_replication_factor_value }}
  register: result
  failed_when:
    - "'already exists' not in result.stderr"
    - "'Created topic' not in result.stdout"
  tags: ["smoke-test-kafka", "smoke-test"]


- name: MapR | Kafka | Validate topic creation
  command: >
    {{ kafka_home_dir }}/bin/kafka-topics.sh
      --list
      --topic {{ kafka_test_topic_name }}
      --zookeeper {{ inventory_hostname }}:{{ zookeeper.port }}
  register: createtopicreturn
  failed_when: "createtopicreturn.stdout != '{{ kafka_test_topic_name }}'"
  tags: [ "smoke-test-kafka", "smoke-test"]

- name: MapR | Kafka | Validate partition and replication factor configurations
  command: >
    {{ kafka_home_dir }}/bin/kafka-topics.sh
      --describe
      --topic {{ kafka_test_topic_name }}
      --zookeeper {{ inventory_hostname }}:{{ zookeeper.port }}
  register: describetopicreturn
  failed_when: "describetopicreturn.stdout.find('PartitionCount:{{ kafka_test_partition_value }}') == true and \
                describetopicreturn.stdout.find('ReplicationFactor:{{ kafka_test_replication_factor_value }}') == true"
  tags: ["smoke-test-kafka", "smoke-test"]