---
- name: MapR | Kafka | Set LOG_DIR used by Kafka run class script tu use the nfs volume
  template: backup=yes src=kafka-server-start.sh.j2 dest={{ kafka_home_dir }}/bin/kafka-server-start.sh mode=0755
  tags: package

- name: MapR | Kafka | Configure with broker id, port, logs, partitions and zookeeper
  template: backup=yes src=kafka.server.properties.j2 dest={{ kafka_home_dir }}/config/server.properties
  tags: package

- name: MapR | Kafka | Copy the kafka-server-status.sh to kafka bin
  copy: src=kafka-server-status.sh dest={{ kafka_home_dir }}/bin mode=0755
  tags: package

- name: MapR | Kafka | Configure warden
  template: backup=yes src=warden.kafka.conf.j2 dest=/opt/mapr/conf/conf.d/warden.kafka.conf owner=mapr group=mapr
  tags: package

- name: MapR | Kafka | Wait warden restart
  service: name=mapr-warden state=restarted
  tags: package

