---

- name: "Install HAProxy"
  package: name=haproxy
  tags: package

- name: "HAProxy | Suppress tmp store first to assemble"
  file: path=/tmp/ssl_stores state=absent
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )

- name: "HAProxy | Create tmp store first to assemble"
  file: path=/tmp/ssl_stores mode=0644 state=directory
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )

- name: "HAProxy | Copy mcs keys to remote"
  copy:
    src: "{{ inventory_dir }}/resources/hue_keys/{{ item }}"
    dest: "/tmp/ssl_stores/{{ item }}"
  with_items:
    - hue.key
    - hue.pem
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )

- name: "HAProxy | Certificat and key concatenation"
  assemble:
    src=/tmp/ssl_stores
    dest=/etc/haproxy/hue.keypem
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )

- name: "HAProxy | Assign variable bind for haproxy.cfg"
  set_fact:
      haproxy_bind_parameter: "ssl crt /etc/haproxy/hue.keypem"
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )

- name: "HAProxy | Assign variable ssl-check for haproxy.cfg"
  set_fact:
      haproxy_ssl_check_parameter: "ssl verify none"
  when: ("{{ inventory_hostname in groups['mapr-ha-node'] }}" ) and (hue_with_certificat == True )
