- name: restart MySQL
  service: name="{{ ansible_distribution_major_version == '6' | ternary('mysqld', 'mariadb') }}" state=restarted enabled=true
  when:   ansible_distribution_major_version == '6'
